### ISSUE TITLE
light tunnel above uv leds scratches pcb

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#1]
The anodized black tunnel between bottom pcb (uv leds) and mainboard and the metallic-silver light funnel inside it scratch the bottom and main pcb. The protective layer of varnish above the copper paths of the pcb can be scratched away when the printer is transported due to the vibrations of the movement.

In my case this resulted in the touchscreen not working or sometimes showing distorted pages.

To repair Alfredo wrote:

> It may be that there is an exposed track on the main board that is touching the black aluminum tube, the one under the mask display. To check, please carefully remove the 2 M2 screws holding the linear guide to the rear aluminum plate of the cover (the bottom one and the top one, which have the nut). Then remove all 12 black M3 screws from the base of the machine. Disconnect the 4-wire cable that connects the main board to the base board. Check that there are no exposed tracks around the display (it will look gold), at the bottom of the main board and around the mask display. If so, simply place a piece of electrical tape over the exposed track and reassemble.

Examples for broken menu pages:
![1 screen showing broken menu](https://github.com/user-attachments/assets/6fb9e6fa-e1d6-4238-8492-e64e9a1ef58c)
![2 screen showing broken menu white background](https://github.com/user-attachments/assets/6fe46c02-680b-42cf-b07c-e468753fa24c)

Scratches on the main pcb leaving the paths blank:
![4 scratches mainboard other corner geaendert](https://github.com/user-attachments/assets/61a19d3a-b51b-4551-bf8a-fbd302da99e3)
![5 scratch mainboard near UK geaendert](https://github.com/user-attachments/assets/dd2acca2-7d15-4df7-a7b1-f951fc06a21c)

Bottom pcb with paths covered where metal touches them:
**WARNING: the tape I used in the picture might not resist the heat emitted by the leds.**
![6 base pcb protected with tape geaendert](https://github.com/user-attachments/assets/959545c8-060b-4d0e-9c30-c9030cb05b6d)

Metal tube with edge covered with tape:
![7 metal tube corner closeup tape geaendert](https://github.com/user-attachments/assets/2990f6f4-6234-4f65-ae9e-94db271b7856)

**Comment by chri2** [comment]
Better idea than tape to insulate:

Print some thin layers based on the [dimension of the tube and cone](https://github.com/Lite3DP/Lite3DP-Gen-2/blob/main/Hardware/Plastic%20parts/Cone.STL) and some washers of the same thickness to put between tube and PCBs.

If I'll find time to do that, I'll publish the stl here.

**Comment by Lite3DP** [comment]
Solution added to [Troubleshooting guide](https://github.com/Lite3DP/Lite3DP-Gen-2/tree/main/Troubleshooting).
