### ISSUE TITLE
directory on sdcard not selectable in menu

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#12]
On my sdcard I have two directories with png files for printing two objects:

```sh
$ ls -l
insgesamt 144
drwxr-xr-x 2 cvogel cvogel 114688  3. Okt 15:47 rmote5
drwxr-xr-x 2 cvogel cvogel  32768  6. Okt 10:50 top1
```

The printer let's me only select the `top1` directory.

* put the rmote5 directory on the card
* printed rmote5 successfully
* put top1 directory on card
* only top1 selectable

## Update

Put another directory on the card:

```sh
$ ls -l
insgesamt 320
drwxr-xr-x 2 cvogel cvogel 114688  3. Okt 15:47 rmote5
drwxr-xr-x 2 cvogel cvogel 196608  6. Okt 10:47 top1
drwxr-xr-x 2 cvogel cvogel  16384  7. Okt 12:28 top2
```

Now I can see `top1` and `top2` in the Lite3DPs menu, **but not** `rmote5`.

## yet another update

The directories from the following output can all be printed.

```
$ ls -l
insgesamt 864
drwxr-xr-x 2 cvogel cvogel 114688 20. Okt 11:01 rmote
drwxr-xr-x 2 cvogel cvogel  16384 16. Okt 23:39 slice1
drwxr-xr-x 2 cvogel cvogel  49152 17. Okt 23:00 slice2
drwxr-xr-x 2 cvogel cvogel 196608  6. Okt 10:47 top1
drwxr-xr-x 2 cvogel cvogel 311296 15. Okt 21:11 Top1g
drwxr-xr-x 2 cvogel cvogel 196608  7. Okt 14:45 top2
```

I had to **rename `rmote5*`** to `rmote*`. **Before renaming** only all the other directories were shown in the menu.

Again, when **only `rmote5` has been on the sdcard** it has been shown in the menu and I printed it successfully.

**Comment by Lite3DP** [comment]
The application reads the files on the micro SD card just before allowing their selection. If you add a new file to the micro SD card you must return to a previous screen.
