### ISSUE TITLE
feature request: use sdcard for printing presets

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#13]
It would be really nice if it would be possible to use the sdcard for printer settings, too.

Doing so it would be easy to archive them or publish them for comparison.

Also it would be really nice if settings could be put into a folder containing layer images. The settings in the folder (or with the same name as the folder and some file extensions) could then be offered to be used for printing on the menu.

This would make it very easy to exchange already tested prints composed of an archive containing the sliced images and the printer settings used.

If the printer settings would be in a file format that'd allow multiple sections (like toml or yaml) they could contain sections for different types of resin as well.

**Comment by Lite3DP** [comment]
Not for now.
