### ISSUE TITLE
only one directory on sdcard visible

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#17]
Some point at time after upgrading to firmware 1.1 I found that the selection for printing objects saved on sdcard does only show one of the entries on the sdcard.

I tried various different naming like `A_B`, `B`, `A`, `test`. If there are two directories on the sdcard I can only select one of them and the other does not show up in the menu of the printer.

I took care to copy all the files before inserting the sdcard into the printer and then switching it on.

I formated a second (different) sdcard, tried that and it didn't change anything.

**Comment by Lite3DP** [comment]
It's not a problem with v1.1. Please check with another micro SD card, format it, etc.
