### ISSUE TITLE
touchscreen went black on longer print

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#2]
When printing the _touchpen_ testprint the screen at some point went black, but the print went through with no errors.

Might be related to https://github.com/Lite3DP/Lite3DP-Gen-2/issues/1

**Comment by Lite3DP** [comment]
Solution added to [Troubleshooting guide](https://github.com/Lite3DP/Lite3DP-Gen-2/tree/main/Troubleshooting).
