### ISSUE TITLE
The progression display is printed

### ISSUE THREAD

**Issue by neolao** [Lite3DP/Lite3DP-Gen-2#5]
I tried to print the touchpen and the result is this:

![ea13878a-b6c0-4cdb-9c7c-ce6aa4b53856](https://github.com/user-attachments/assets/9c57eb55-600a-44cf-a7cc-545e1d491af3)

You can see "99" and "TO FINISH". 
I suppose that the image destined to the touch screen was used to print.
I can also say that the images (the sliced model + touch screen display) are merged.

**Comment by chri2** [comment]
I had a similar issue: I selected a folder from the sdcard and briefly a yellow printed `Preview` appeared at the bottom of a otherwise black screen. Then the screen jumped to the `PARAMETERS` menu page.

I started the print and got something I think is the menu.
![DSC07459](https://github.com/user-attachments/assets/8fac1fcd-260e-489a-b8df-e17bed8aa35c)

**Comment by jene8774** [comment]
+1 
It seems to be a bug that happens across the board, not an individual error.

**Comment by chri2** [comment]
To check @jene8774 idea about the additional files which are not images of layers I started a print as generated by PrusaSlicer. The directory contains the following files:
```
$ ls -nl | head -n4; echo '[...]'; ls -nl | tail -n4
insgesamt 2336
-rw-r--r-- 1 1000 1000  419 29. Sep 13:31 config.ini
-rw-r--r-- 1 1000 1000 3004 29. Sep 13:31 prusaslicer.ini
-rw-r--r-- 1 1000 1000 2500 29. Sep 13:31 rmote300000.png
[...]
-rw-r--r-- 1 1000 1000  333 29. Sep 13:31 rmote300578.png
-rw-r--r-- 1 1000 1000  318 29. Sep 13:31 rmote300579.png
-rw-r--r-- 1 1000 1000  287 29. Sep 13:31 rmote300580.png
drwxr-xr-x 2 1000 1000 4096 29. Sep 13:32 thumbnail
```

So there are at least two files that are not layer images and maybe the subdirectory will be counted as an additional file also.

**Comment by neolao** [comment]
Oh I see. I will try removing unnecessary files

**Comment by chri2** [comment]
related to #8
