### ISSUE TITLE
Setting for Supports for PrusaSlicer in Quick Start Guide missing?

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#7]
https://github.com/Lite3DP/Lite3DP-Gen-2/blob/main/Gen%202%20-%20Quick%20Start%20Guide/Gen%202%20-%20slicer%20configuration.pdf

One of my first prints with supports didn't come out good, because the support beams weren't connected to the object.

![remote part - supports too small 2](https://github.com/user-attachments/assets/56a31b06-a38c-4881-aaa2-b591e841e52e)

Looking around in PrusaSlicer I found a setting for how thick the supports should be at there ending and increased that.

![1st succesfull print - menu included 1](https://github.com/user-attachments/assets/796daecd-df18-478d-862e-021193431e20)

It became better. I'm just printing now another test with `Print Settings / Supports / Pinhead front diameter` set to 0.75mm to test whether this helps to improve.

**Comment by Lite3DP** [comment]
Support features must be set according to the part to be printed and the resin used. There is no universal setting.
