### ISSUE TITLE
silicon covers for vat are too small

### ISSUE THREAD

**Issue by chri2** [Lite3DP/Lite3DP-Gen-2#9]
I can only make the top cover to stay on the vat with a lot of trying and pushing it back on.

[2024-09-30-130633.webm](https://github.com/user-attachments/assets/21945607-80e7-4c4a-9804-282022fd49cf)

**Comment by Lite3DP** [comment]
Solution added to (Troubleshooting guide)[https://github.com/Lite3DP/Lite3DP-Gen-2/tree/main/Troubleshooting].
